questionic/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
app_name = 'questionic'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('post_question/', views.post_question, name='post_question'),
    path('question/<int:question_id>', views.question, name='question'),
    path('notification/', views.notification, name='notification'),
    path('notification_alert/', views.notification_alert, name='notification_alert'),
    path('search/', views.search, name='search'),
    path('report/<str:type_report>/<int:report_id>', views.report, name='report'),
    path('delete/<str:type>/<int:id>', views.delete, name='delete'),
    path('fav_question/<int:question_id>/<str:status>', views.fav_question, name='fav_question'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questionic_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('questionic.urls')),
    path('users/', include('users.urls', namespace='users')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('signup', views.signup, name='signup'),
    path('editprofile', views.editprofile, name='editprofile'),
    path('<str:status>/<str:userf>', views.follow, name='follow'),
    path('<str:username>', views.userprofile, name='userprofile'),
]

questionic/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Question, Account, QuestionFile, Answer, AnswerFile
from .models import ReplyAnswer, ReplyAnswerFile, Notification
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import JsonResponse
from django.utils.timezone import datetime

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        question_lastest = Question.objects.all().order_by("-date_asked")[:10]
        question_popular = Question.objects.all().order_by('-faved')[:10]

        return render(request, 'questionic/index.html', {
            "question_lastest": question_lastest,
            "question_popular": question_popular,
            "time_now": datetime.now(),
        })

    user = User.objects.get(username=request.user.username)
    account = Account.objects.get(user=user)
    notification = Notification.objects.get(account=account)
    notification_alert = notification.alert_notification()

    question_lastest = Question.objects.all().order_by("-date_asked")[:10]
    question_popular = Question.objects.all().order_by('-faved')[:10]

    return render(request, 'questionic/index.html', {
        "notification_alert": notification_alert,
        "account": account,
        "question_lastest": question_lastest,
        "question_popular": question_popular,
        "time_now": datetime.now(),
    })

def about(request):
    if not request.user.is_authenticated:
        return render(request, 'questionic/about.html')
    user = User.objects.get(username=request.user.username)
    account = Account.objects.get(user=user)
    notification = Notification.objects.get(account=account)

    notification_alert = notification.alert_notification()
    return render(request, 'questionic/about.html', {
        "notification_alert": notification_alert,
        "account": account
    })

def post_question(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    
    user = User.objects.get(username=request.user.username)
    account = Account.objects.get(user=user)
    notification = Notification.objects.get(account=account)

    if request.method == 'POST':

        # tags = request.POST['Tags']
        title = request.POST['Title']
        detail = request.POST['Detail']
        category = request.POST['Category']
        grade = request.POST['Grade']
        asker = Account.objects.get(user=user)
        images = request.FILES.getlist('images')

        question = Question.objects.create(title=title, detail=detail,  category=category, grade=grade, asker=asker)

        for img in images:
            QuestionFile.objects.create(question=question, image=img)

        follower = Account.objects.filter(following=user.id)
        for person in follower:
            Notification.objects.get(account=person).follow_notification.add(question)

        return HttpResponseRedirect(reverse('questionic:question', args=(question.id, ))) 
         
        
    notification_alert = notification.alert_notification()  
    return render(request, 'questionic/post_question.html', {
        "notification_alert": notification_alert,
        "account": account
    })

def question(request, question_id):
   
    if not request.user.is_authenticated:
        # Question
        question = Question.objects.get(id=question_id)
        list_images = QuestionFile.objects.filter(question=question)

        #Comment
        list_answer = Answer.objects.filter(from_question=question)

        dict_answer_image = {}
        dict_reply_image = {}
        for ans in list_answer:
            answerfile = AnswerFile.objects.filter(answer=ans)
            dict_answer_image.update({ans: answerfile})

            replyanswer = ReplyAnswer.objects.filter(from_answer=ans)
            dict_replyanswer = {}
            for reans in replyanswer:
                replyanswerfile = ReplyAnswerFile.objects.filter(reply_answer=reans)
                dict_replyanswer.update({reans: replyanswerfile})
            dict_reply_image.update({ans: dict_replyanswer})
        return render(request, 'questionic/question.html', {
        'question': question,
        'list_images': list_images,
        'dict_answer_image': dict_answer_image,
        'dict_reply_image': dict_reply_image,
    })

    user = User.objects.get(username=request.user.username)
    myaccount = Account.objects.get(user=user)
    account = Account.objects.get(user=user)
    notification = Notification.objects.get(account=myaccount)
    notification_alert = notification.alert_notification()

    if request.method == 'POST':

        if  request.POST.get('comment'):
            detail = request.POST['Detail']
            images = request.FILES.getlist('images')
            from_question = Question.objects.get(id=request.POST['comment'])
            answerer = Account.objects.get(user=user)
            answer=Answer.objects.create(detail = detail, from_question=from_question, answerer=answerer)
            from_question.answer_count = from_question.answer.count()
            from_question.save()
            for image in images:
                AnswerFile.objects.create(answer=answer, image=image)
            
            if not from_question.asker == answerer:
                Notification.objects.get(account=from_question.asker).reply_notification.add(answer)
                
        elif request.POST.get('reply'):
            detail = request.POST['Detail']
            images = request.FILES.getlist('images')
            from_answer = Answer.objects.get(id=request.POST['reply'])
            reply_answerer = Account.objects.get(user=user)
            reply_answer = ReplyAnswer.objects.create(detail = detail, from_answer=from_answer, reply_answerer=reply_answerer)
            for image in images:
                ReplyAnswerFile.objects.create(reply_answer=reply_answer, image=image)
    
     # Question
    question = Question.objects.get(id=question_id)
    list_images = QuestionFile.objects.filter(question=question)

    #Comment
    list_answer = Answer.objects.filter(from_question=question)

    dict_answer_image = {}
    dict_reply_image = {}
    for ans in list_answer:
        answerfile = AnswerFile.objects.filter(answer=ans)
        dict_answer_image.update({ans: answerfile})

        replyanswer = ReplyAnswer.objects.filter(from_answer=ans)
        dict_replyanswer = {}
        for reans in replyanswer:
            replyanswerfile = ReplyAnswerFile.objects.filter(reply_answer=reans)
            dict_replyanswer.update({reans: replyanswerfile})
        dict_reply_image.update({ans: dict_replyanswer})
    
    return render(request, 'questionic/question.html', {
        'question': question,
        'list_images': list_images,
        'myaccount': myaccount,
        'dict_answer_image': dict_answer_image,
        'dict_reply_image': dict_reply_image,
        'notification_alert': notification_alert,
        "account": account
    })

def fav_question(request, question_id, status):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))

    user = User.objects.get(username=request.user.username)
    account = Account.objects.get(user=user)
    if status == 'fav':
        question = Question.objects.get(id=question_id)
        account.fav_question.add(question)
        account.save()
        question.faved = question.fav_account.count()
        question.save()

    elif status == 'unfav':
        question = Question.objects.get(id=question_id)
        account.fav_question.remove(question)
        account.save()
        question.faved = question.fav_account.count()
        question.save()
    
    return HttpResponseRedirect(reverse('questionic:question', args=(question_id, )))
    

def notification(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))

    user = User.objects.get(username=request.user.username)
    account = Account.objects.get(user=user)
    notification = Notification.objects.get(account=account)
    new_noti = {
        'reply': notification.alert_reply_notification(), 
        'follow': notification.alert_follow_notification(),
        'qreport': notification.alert_qreport_notification(), 
        'areport': notification.alert_areport_notification(), 
        'rreport': notification.alert_rreport_notification()
        }

    notification.reply_notification_count = notification.reply_notification.count()
    notification.follow_notification_count = notification.follow_notification.count()
    notification.save()
    
    notification_alert = notification.alert_notification()
    reply_notifications = notification.reply_notification.all().order_by('-date_answered')
    follow_notifications = notification.follow_notification.all().order_by('-date_asked')
    
    if request.user.is_staff:
        notification.qreport_notification_count = notification.qreport_notification.count()
        notification.areport_notification_count = notification.areport_notification.count()
        notification.rreport_notification_count = notification.rreport_notification.count()
        notification.save()

        qreport_notifications =  notification.qreport_notification.all().order_by('-date_asked')
        areport_notifications =  notification.areport_notification.all().order_by('-date_answered')
        rreport_notifications =  notification.rreport_notification.all().order_by('-date_reply_answered')
        return render(request, 'questionic/notification.html', {
            "notification_alert": notification_alert,
            "new_noti": new_noti,
            "reply_notifications": reply_notifications,
            "follow_notifications": follow_notifications,
            "qreport_notifications": qreport_notifications,

questionic/templates/questionic/about.html
{% extends 'questionic/layout.html' %}
{% block body %}

<div class="container">
    <br>
    <h1 style="text-align:center;">About Us</h1>
    <br>
    <div class="row g-0">
        {% comment %} <div class="col-3"></div> {% endcomment %}
        <div class="col-6">
            <h2 style="text-align:center;">Member</h2>
            <div class="table-responsive">
                <table class="table table-borderless">
                    <thead>
                        <tr>
                          <th scope="col">ชื่อ-นามสกุล</th>
                          <th scope="col">เลขทะเบียนนักศึกษา</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>พิตตินันท์ เลิศสิริมั่นคง</th>
                            <td>6210612658</td>
                        </tr>
                        <tr>
                            <td>นนทิชา หลิมศิโรรัตน์</th>
                            <td>6310682585</td>
                        </tr>
                        <tr>
                            <td>พิชญา อินทร์พิบูลย์</th>
                            <td>6310682627</td>
                        </tr>
                        <tr>
                            <td>ไพศาล แซ่โล</th>
                            <td>6310682809</td>
                        </tr>
                        <tr>
                            <td>นัฐวุฒิ พิชัยกาล</th>
                            <td>6310682817</td>
                        </tr>
                    </tbody>
                </table>
              </div>
        </div>
        <div class="col-6">
            <h2 style="text-align:center;">Link</h2>
            <div class="table-responsive">
                <table class="table table-borderless">
                    <tr>
                        <th scope="row"><img src="https://cdn-icons-png.flaticon.com/512/733/733609.png" width="20" height="20"></th>
                        <td><a href="https://github.com/6310682817/questionic.git"> Github Repoitory</a></td>
                    </tr>
                    <tr>
                        <th scope="row"><img src="https://seeklogo.com/images/P/pivotal-tracker-logo-8D74DF11DA-seeklogo.com.png?v=637829618590000000" width="20" height="20"></th>
                        <td><a href="https://www.pivotaltracker.com/n/projects/2608644"> pivotaltracker</a></td>
                    </tr>
                </table>
              </div>
        </div>
    </div>
</div>

{% endblock %}

questionic/templates/questionic/layout.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Questionic</title>
        <meta charset="utf-8">
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/1763/1763016.png">
        <link rel="stylesheet" href="{% static 'css/notification.css' %}">
        <link rel="stylesheet" href="{% static 'css/question.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    
        <!-- Font Awesome -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
        <!-- MDB -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.css" rel="stylesheet"/>
        <!-- MDB -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.js"></script>
        <style>
          .logo{
              color: #000;
              font-size: 25px;
              font-weight: 700;
          }
        </style>
        <script src="https://cdn.tiny.cloud/1/ivgfsy3op8dcdo67r7m4kalo70imr8acsz9frooi6aaqx59d/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
        <script>
          tinymce.init({
            selector: 'textarea#editor',
            skin: 'bootstrap',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage tableofcontents footnotes mergetags autocorrect codesample',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat | codesample',
            menubar: false,
            statusbar: false,
            });
        </script>
    
    </head>
    <body>
        {% block nav %}
          <!-- Navbar-->
          <nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding-left:30px;">
              <div class="container-fluid justify-content-between">
                <!-- Left elements -->
                <div class="d-flex">
                  <!-- Brand -->
                  <a class="navbar-brand me-2 mb-1 d-flex align-items-center" href="{% url 'questionic:index' %}">
                      <div class="logo">Questionic</div>
                  </a>
            
                  <!-- Search form -->
                  <form action="{% url 'questionic:search' %}" method="get" class="input-group w-auto my-auto d-none d-sm-flex">
                    <input autocomplete="off" type="search" name="search_keyword" class="form-control rounded" placeholder="Search" style="min-width: 125px; margin-left:30px;"/>
                    <span class="input-group-text border-0 d-none d-lg-flex"><i class="fas fa-search"></i></span>
                  </form>
                </div>
                <!-- Left elements -->
          
                <!-- Right elements -->
                {% if user.is_authenticated %}
                <ul class="navbar-nav flex-row">
                  <li class="nav-item me-3 me-lg-1">
                    <a class="nav-link d-sm-flex align-items-sm-center" href="{% url 'users:index' %}">
                      
                      <img src="{{account.image_profile.url}}" class="rounded-circle" height="22" alt="Black and White Portrait of a Man" loading="lazy"/>
                      <strong class="d-none d-sm-block ms-1">{{account.user}}</strong>
                    </a>
                  </li>
                  <li class="nav-item me-3 me-lg-1">
                    <a class="nav-link" href="{% url 'questionic:post_question' %}">
                      <span><i class="fas fa-plus-circle fa-lg"></i></span>
                    </a>
                  </li>
                  <li class="nav-item me-3 me-lg-1">
                    <a class="nav-link" href="{% url 'questionic:notification' %}">
                      <i class="fas fa-bell fa-lg"></i>
                      <span id="badge_alert" class="badge rounded-pill badge-notification bg-danger">{{notification_alert}}</span>

                    </a>
                  </li>
                  
                  <li class="nav-item dropdown me-3 me-lg-1">
                    <a class="nav-link dropdown-toggle hidden-arrow" href="{% url 'questionic:notification' %}" id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                      <i class="fas fa-chevron-circle-down fa-lg"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                      <li>
                        <a class="dropdown-item" href="{% url 'questionic:about' %}">About</a>
                      </li>
                      <li>
                        <a class="dropdown-item" href="{% url 'users:editprofile' %}">Edit Profile</a>
                      </li>
                      <li>
                        <a class="dropdown-item" href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i> Log out</a>
                      </li>
                    </ul>
                  </li>
                  
                </ul>
                
              </div>
                {% else %}
                <div class="d-flex align-items-center">
                  <a href="{% url 'users:login'%}">
                  <button type="button" class="btn btn-link px-3 me-2">
                    Login
                  </button>
                </a>
                <a href="{% url 'users:signup'%}">
                  <button type="button" class="btn btn-primary me-3">
                    Sign up
                  </button>
                </a>
                </div>
                {% endif %}
                <!-- Right elements -->
              </div>
            </nav>
            <!-- Navbar -->
        
        {% endblock%}
        {% block body %}
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
    </body>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        function loadDoc() {
            const xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function() {
                if (xhttp.readyState === XMLHttpRequest.DONE) {
                    const status = xhttp.status;
                    if (status === 0 || (status >= 200 && status < 400)) {
                        data = JSON.parse(this.responseText)
                        document.getElementById("badge_alert").innerHTML = data.notification_alert;
                    }
                }
            }
            xhttp.open("GET", "{% url 'questionic:notification_alert'%}");
            xhttp.send(); 
        }
          
        setInterval(function() {
            loadDoc();
        },5000);
    </script>
</html>

questionic/templates/questionic/post_question.html
{% extends 'questionic/layout.html' %}
{% block body %}




<div class="container" style="margin-top:50px;">
  <div class="row gx-xl-5">
      <div class="col-xl mb-lg-5 pr-cl-4">
        <div class="card mb-5">
          <div class="card-body" style="padding:20px 30px 10px 20px;">
          
            <h1>สร้างโพสต์คำถาม</h1>

            <form action="{% url 'questionic:post_question' %}" method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
                {% csrf_token %}
                
                <label for="Title">หัวข้อ :
                <input class="form-control" type="text" name="Title" placeholder="หัวข้อ" required>
                <div class="invalid-feedback">
                  กรุณาใส่หัวข้อ
                </div>
                <br><br>
                <h6>รายละเอียด : </h6>
                <div class="form-group">
                  <textarea id="editor" name="Detail"></textarea>
                </div>
                <div class="invalid-feedback">
                  กรุณาใส่รายละเอียด
                </div>
                <br><br>

                <label for="Category">หมวดหมู่ :
                <select name="Category" class="form-select" required> 
                    <option value="">--กรุณาเลือกหมวดหมู่--</option>
                    <option value="คณิตศาสตร์">คณิตศาสตร์</option>
                    <option value="วิทยาศาสตร์">วิทยาศาสตร์</option>
                    <option value="ภาษาและวัฒนธรรมไทย">ภาษาและวัฒนธรรมไทย</option>
                    <option value="ภาษาต่างประเทศ">ภาษาต่างประเทศ</option>
                    <option value="สังคมศึกษา">สังคมศึกษา</option>
                    <option value="วิชาชีพ">วิชาชีพ</option>
                    <option value="พลศึกษา">พลศึกษา</option>
                    <option value="ศิลปะ">ศิลปะ</option>
                    <option value="คอมพิวเตอร์">คอมพิวเตอร์</option>
                    <option value="อื่นๆ">อื่นๆ</option>
                  </select>
                  <div class="invalid-feedback">
                    กรุณาเลือกหมวดหมู่
                  </div>
                <br><br>

                <label for="Grade">ระดับชั้น :
                <select name="Grade" class="form-select" required> 
                    <option value="">--กรุณาเลือกระดับชั้น--</option>
                    <option value="ป.1">ป.1</option>
                    <option value="ป.2">ป.2</option>
                    <option value="ป.3">ป.3</option>
                    <option value="ป.4">ป.4</option>
                    <option value="ป.5">ป.5</option>
                    <option value="ป.6">ป.6</option>
                    <option value="ม.1">ม.1</option>
                    <option value="ม.2">ม.2</option>
                    <option value="ม.3">ม.3</option>
                    <option value="ม.4">ม.4</option>
                    <option value="ม.5">ม.5</option>
                    <option value="ม.6">ม.6</option>
                  </select>
                  <div class="invalid-feedback">
                    กรุณาเลือกระดับชั้น
                  </div>
                <br><br>

                <label for="Tags">แท็ก :
                <input class="form-control" type="text" name="Tags" ><br><br>

                <label for="">รูปภาพ (.png และ .jped เท่านั้น): 
                <input class="form-control" type="file" name="images" accept="image/png, image/jpeg" multiple><br><br>


                <input class="btn btn-secondary btn-sm" type="submit" value="สร้างโพสต์">
            </form>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  (() => {
    'use strict'

    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    const forms = document.querySelectorAll('.needs-validation')

    // Loop over them and prevent submission
    Array.from(forms).forEach(form => {
      form.addEventListener('submit', event => {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }

        form.classList.add('was-validated')
      }, false)
    })
  })()
</script>

{% endblock %}

questionic/templates/questionic/search.html
{% extends 'questionic/layout.html' %}
{% block body %}
<div class="container" style="margin-top:50px;">
    <div class="row gx-xl-5">
        <div class="col-xl mb-lg-5 pr-cl-4">
          <h2>Search: {{search_keyword}}</h2>

          <div class="card mb-5">
            <form action="{% url 'questionic:search' %}" method="get">
                <div class="input-group">
                    <div class="form-outline">
                      <input type="search" name="search_keyword" id="search_input" class="form-control" placeholder="พิมพ์คำค้นหา" aria-label="Search" />
                    </div>
                    <button type="submit" class="btn btn-primary">
                      <i class="fas fa-search"></i>
                    </button>
                  </div>
                  <br>
                  <div style="display:flex;">
                    
                        <select id="category" name="category" class="form-select"> 
                            <option value="">กรองหมวดหมู่</option>
                            <option value="คณิตศาสตร์">คณิตศาสตร์</option>
                            <option value="วิทยาศาสตร์">วิทยาศาสตร์</option>
                            <option value="ภาษาและวัฒนธรรมไทย">ภาษาและวัฒนธรรมไทย</option>
                            <option value="ภาษาต่างประเทศ">ภาษาต่างประเทศ</option>
                            <option value="สังคมศึกษา">สังคมศึกษา</option>
                            <option value="วิชาชีพ">วิชาชีพ</option>
                            <option value="พลศึกษา">พลศึกษา</option>
                            <option value="ศิลปะ">ศิลปะ</option>
                            <option value="คอมพิวเตอร์">คอมพิวเตอร์</option>
                            <option value="อื่นๆ">อื่นๆ</option>
                        </select>

        
                  
                        <select id="grade" name="grade" class="form-select"> 
                            <option value="">กรองระดับชั้น</option>
                            <option value="ป.1">ป.1</option>
                            <option value="ป.2">ป.2</option>
                            <option value="ป.3">ป.3</option>
                            <option value="ป.4">ป.4</option>
                            <option value="ป.5">ป.5</option>
                            <option value="ป.6">ป.6</option>
                            <option value="ม.1">ม.1</option>
                            <option value="ม.2">ม.2</option>
                            <option value="ม.3">ม.3</option>
                            <option value="ม.4">ม.4</option>
                            <option value="ม.5">ม.5</option>
                            <option value="ม.6">ม.6</option>
                        </select>
                        <select id="status" name="status" class="form-select"> 
                            <option value="">กรองสถานะคำถาม</option>
                            <option value="unanswer">ยังไม่มีคำตอบ</option>
                            <option value="answer">มีคำตอบแล้ว</option>
                        </select>
                    </div>
                  
                
                
              </form>   
          </div>

          <br>
          {% for question in question_search %}
              <div class="card mb-5">
                <div class="card-body" style="padding:20px 30px 10px 20px;">
                  <div style="display: flex; justify-content: space-between;">
                    <a href="{% url 'questionic:question' question.id %}">
                      <h3>{{question.title}}</h3>
                    </a>
                    <p>ชอบ : {{question.faved}}</p>
                  </div>
                  <p>รายละเอียด : {{question.detail|safe|truncatechars:50}}</p>
                  <p>ระดับ : {{question.grade}} / หมวดหมู่ : {{question.category}}</p>
                  <div style="display: flex; justify-content: space-between;">
                    <div style="display: flex;">
                      <img src="{{question.asker.image_profile.url}}" width="20px" height="20px">
                      <p>&nbsp&nbsp{{question.asker }}</p>
                    </div>
                    {% if question.date_asked.day == time_now.day %}
                    <p> {{question.date_asked|timesince }} ago</p>
                    {% else %}
                    <p> {{question.date_asked|date:'M d, Y H:i'}}</p>
                    {% endif %}
                  </div>
                </div>
              </div>
            {% endfor %}
        </div>
    </div>
</div>
  <script>
    document.getElementById("search_input").value = '{{search_keyword}}';
    document.getElementById("category").value = '{{category}}';
    document.getElementById("grade").value = '{{grade}}';
    document.getElementById("status").value = '{{status}}';
  </script>
{% endblock %}