questionic/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
app_name = 'questionic'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('post_question/', views.post_question, name='post_question'),
    path('question/<int:question_id>', views.question, name='question'),
    path('notification/', views.notification, name='notification'),
    path('notification_alert/', views.notification_alert, name='notification_alert'),
    path('search/', views.search, name='search'),
    path('report/<str:type_report>/<int:report_id>', views.report, name='report'),
    path('delete/<str:type>/<int:id>', views.delete, name='delete'),
    path('fav_question/<int:question_id>/<str:status>', views.fav_question, name='fav_question'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questionic_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('questionic.urls')),
    path('users/', include('users.urls', namespace='users')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('signup', views.signup, name='signup'),
    path('editprofile', views.editprofile, name='editprofile'),
    path('<str:status>/<str:userf>', views.follow, name='follow'),
    path('<str:username>', views.userprofile, name='userprofile'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from questionic.models import Account, Notification, Question
from django.utils.timezone import datetime

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))

    user = User.objects.get(username=request.user.username)
    account = Account.objects.get(user=user)
    notification = Notification.objects.get(account=account)
    following = Account.objects.filter(follower=user.id).count()
    follower = Account.objects.filter(following=user.id).count()
    if Question.objects.filter(asker=account).count() == 0:
        post_history = []
    else:
        post_history = Question.objects.filter(asker=account).all().order_by("-date_asked")

    notification_alert = notification.alert_notification()
    return render(request, 'users/index.html', {
        'notification_alert': notification_alert,
        'account': account,
        'following' : following,
        'follower' : follower,
        'post_history' : post_history,
        'time_now': datetime.now(),
    })

def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        else:
            return render(request, 'users/login.html', {
                'message': 'Invalid credentials.'
            })
    return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('questionic:index'))
    # return render(request, 'users/login.html', {
    #     'message': 'you are logged out.'
    # })

def signup(request):
    if request.method == "POST":
        umessage = ''
        pmessage = ''

        username = request.POST["username"]
        password = request.POST["password"]
        cpassword = request.POST["password confirmation"]
        email = request.POST["email"]
        first_name = request.POST["firstname"]
        last_name = request.POST["lastname"]

        # check username
        if username == '' :
            umessage = 'please enter username.'
        else :
            account = User.objects.filter(username=username).count()
            if account != 0 :
                umessage = 'this username is already taken.'
        
        # check password
        if password == '' :
            pmessage = 'please enter password.'
        if password != cpassword :
            pmessage = 'confirm password is not same as password.'
        
        if umessage == '' and pmessage == '':
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            
            account = Account.objects.create(user=user)
            account.image_profile = '../static/assets/default_profile/profile-pic ('+ str(int(account.id) % 16)+').png'
            account.save()

            Notification.objects.create(account=account)

            return render(request, 'users/login.html')

        else:
            return render(request, 'users/signup.html', {
                'usermessage': umessage,
                'passwordmessage': pmessage,
                'username' : username,
                'password' : password,
                'cpassword' : cpassword,
                'email' : email,
                'first_name' : first_name,
                'last_name' : last_name,
            })
    return render(request, 'users/signup.html')

def userprofile(request, username):
    account = User.objects.filter(username=username).count()
    if account == 0 :
            return HttpResponse('User Not Found.', status = 400)

    if username == request.user.username:
        return HttpResponseRedirect(reverse('users:index'))

    user = User.objects.get(username=username)
    user_account = Account.objects.get(user=user)
    following = Account.objects.filter(follower=user.id).count()
    follower = Account.objects.filter(following=user.id).count()

    if request.user.is_authenticated:
        status = Account.objects.filter(user=request.user.id, following=user.id).count()
        if status == 0:
            follow_status = 'Follow'
        elif status == 1:
            follow_status = 'Unfollow'
    else:
        follow_status = 'Follow'

    if Question.objects.filter(asker=user_account).count() == 0:
        post_history = []
    else:
        post_history = Question.objects.filter(asker=user_account).all().order_by("-date_asked")
    
    return render(request, 'users/userprofile.html', {
        "follow_status" : follow_status,
        "username" : username,
        "following" : following,
        "follower" : follower,
        'post_history' : post_history,
    })


def follow(request, status, userf):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    
    user_f = User.objects.get(username=userf)
    userfollow = Account.objects.get(user=user_f.id)
    username = Account.objects.get(user=request.user.id)
    if status == 'Follow':
        username.following.add(userfollow)
    elif status == 'Unfollow':
        username.following.remove(userfollow)
    return HttpResponseRedirect(reverse('users:userprofile', args=(userf,)))

def editprofile(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))

    user = User.objects.get(username=request.user.username)
    account = Account.objects.get(user=user)
    notification = Notification.objects.get(account=account)

    notification_alert = notification.alert_reply_notification()
    if request.method == "POST":
        if request.POST.get("Save Password"):
            pmessage = ''

            password = request.POST["password"]
            if password == '' :
                pmessage = 'please enter password.'
            
            cpassword = request.POST["password confirmation"]
            if password != cpassword :
                pmessage = 'confirm password is not same as password.'
            
            if pmessage != '':
                return render(request, 'users/editprofile.html', {
                    'passwordmessage': pmessage,
                    'type': 'password'
                })
            user.set_password(password)
            user.save()

        elif request.POST.get("Save Profile"):
            image = request.FILES.getlist("image")

            user.first_name = request.POST["firstname"]
            user.last_name = request.POST["lastname"]
            user.email = request.POST["email"]
            user.save()
            for img in image:
                account.image_profile = img
            account.save()

        return HttpResponseRedirect(reverse('users:index'))   
    return render(request, 'users/editprofile.html', {
        "notification_alert": notification_alert,
        "account": account,
        'type': 'profile'
    })

users/templates/users/editprofile.html
{% include 'questionic/layout.html' %}
{% block body %}

<div class="container" style="margin-top:50px;">
    <div class="tab">
        <button class="tablinks" onclick="openNoti(event, 'profile')">แก้ไขโปรไฟล์</button>
        <button class="tablinks" onclick="openNoti(event, 'password')">แก้ไขPassword</button>
    </div>
    <div id="profile" class="tabcontent">
        <div class="row gx-xl-5">
            <div class="col-xl-8 mb-lg-5 pr-cl-4">
                <h1>แก้ไขโปรไฟล์</h1>

                <form action="{% url 'users:editprofile' %}" enctype="multipart/form-data" method="post">
                    {% csrf_token %}

                    <br>
                    <label for="firstname">Firstname :
                    <input class="form-control" type="text" name="firstname" value="{{user.first_name}}" placeholder="First name">

                    <br><br>
                    <label for="lastname">Lasttname :
                    <input class="form-control" type="text" name="lastname" value="{{user.last_name}}" placeholder="Last name">

                    <br><br>
                    <label for="email">Email :
                    <input class="form-control" type="email" name="email" value="{{user.email}}" placeholder="email">
                    
                    <br><br>

                    <label for="">รูปภาพ (.png และ .jped เท่านั้น): 
                    <input class="form-control" type="file" name="image" accept="image/png, image/jpeg">
                    <br>
                    <img src='{{account.image_profile.url}}' class="img-thumbnail" width="200" height="300">
                    <br><br>

                    <input class="btn btn-secondary btn-sm" type="submit" name="Save Profile" value="Save Profile">

                </form>
            </div>
        </div>

    </div>

    <div id="password" class="tabcontent">
        <div class="row gx-xl-5">
            <div class="col-xl-8 mb-lg-5 pr-cl-4">
                <h1>แก้ไขPassword</h1>

                <form action="{% url 'users:editprofile' %}" enctype="multipart/form-data" method="post">
                    {% csrf_token %}

                    {% if passwordmessage %}
                        <div style="color: red">{{ passwordmessage }}</div>
                    {% endif %}
                    <br>
                    <label for="password">รหัสผ่าน :
                    <input class="form-control" type="password" name="password" placeholder="รหัสผ่าน">

                    <br><br>
                    <label for="password confirmation">ยืนยันรหัสผ่าน :
                    <input class="form-control" type="password" name="password confirmation" placeholder="ยืนยันรหัสผ่าน"> 
                    
                    <br><br>

                    <input class="btn btn-secondary btn-sm" type="submit" name="Save Password" value="Save Password">

                </form>
            </div>
        </div>

    </div>
</div>

<script>
    function openNoti(evt, type) {
      var i, tabcontent, tablinks;
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
      }
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      document.getElementById(type).style.display = "block";
      evt.currentTarget.className += " active";
    }
    window.addEventListener("load", (event) => {
        openNoti(event, '{{type}}');
      });
</script>

{% endblock %}

users/templates/users/index.html
{% include 'questionic/layout.html' %}
{% block body %}

<div class="container">
    <div class="row g-0">
      <div class="col-3"></div>
      <div class="col-6">
        <br>
        <h1>Hello {{ request.user.username }}</h1>
        <br>
        <table style="width: 100%; text-align: center;">
            <tr>
                {% if post_history.count == '' %}
                <td>0</td>
                {% else %}
                <td>{{ post_history.count }}</td>
                {% endif %} 
                <td>{{ following }}</td>
                <td>{{ follower }}</td>
            </tr>
            <tr>
                <th>post</th>
                <th>following</th>
                <th>follower</th>
            </tr>
        </table>

        <br>

        <h3>ประวัติการโพสต์</h3>

        <div style="height: 300px; width:100%; overflow:scroll; border:1px solid #ccc;">
            {% for question in post_history %}

                <div class="card mb-5">
                    <div class="card-body" style="padding:20px 30px 10px 20px;">

                        <a href="{% url "questionic:question" question.id%}">โพสต์: {{question.title|truncatechars:50}}</a>  
                        <p>รายละเอียด : {{question.detail|safe|truncatechars:50}}</p>
                        <p>หมวดหมู่ : {{question.category}} {{question.grade}}</p>
                        {% if question.date_asked.day <= time_now.day %}
                        <p>เวลาโพสต์ : {{question.date_asked|timesince }}</p>
                        {% else %}
                        <p>เวลาโพสต์ : {{question.date_asked|date:'M d, Y H:i'}}</p>
                        {% endif %} 

                    </div>
                </div>
            {% empty %}
                <div class="card mb-5">
                    <div class="card-body" style="padding:20px 30px 10px 20px; text-align: center;">
                        <p>ยังไม่มีโพสต์</p>
                        <a href="{% url "questionic:post_question" %}">โพสต์เลย!</a>
                    </div>
                </div>
            {% endfor %}
      </div>

      </div>
      <div class="col-3"></div>
    </div>
  </div>
 
{% endblock %}

users/templates/users/layout_login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
        <link href="{% static 'users/css/styleslogin.css' %}" rel="stylesheet">
    </head>
    
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/layout_login_signup.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>User</title>
        <link href="{% static 'users/css/styles_login_signup.css' %}" rel="stylesheet">
    </head>
    
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/login.html
{% extends 'users/layout_login_signup.html' %}
{% block body %}

<a href="{% url 'questionic:index' %}"><button class="button">Questionic</button></a>

<div id="box">
    <h1>Login</h1>

    {% if message %}
        <div style="color: red">{{ message }}</div>
    {% endif %}

    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <br>
        <input type="submit" value="Login">
    </form>
    
    <br>
    <p1>Don't have an account yet?</p1>
    <br>
    <a href="{% url 'users:signup' %}"><p1>Sign up</p1></a>

</div>

{% endblock %}

users/templates/users/signup.html
{% extends 'users/layout_login_signup.html' %}
{% block body %}

<a href="{% url 'questionic:index' %}"><button class="button">Questionic</button></a>

<div id="box">

    <h1>Sign Up</h1>

    {% if message %}
        <div style="color: red">{{ message }}</div>
    {% endif %}
    <div id="box2">
        <form action="{% url 'users:signup' %}" method="post">
            {% csrf_token %}

            <p2>Username*</p2>
            {% if usermessage %}
                <div style="color: red">{{ usermessage }}</div>
            {% endif %}
            <input type="text" name="username" placeholder="Username" value="{{ username }}">
            
            <br><br>

            <p2>Password*</p2>
            {% if passwordmessage %}
                <div style="color: red">{{ passwordmessage }}</div>
            {% endif %}
            <input type="password" name="password" placeholder="Password" value="{{ password }}">
            <input type="password" name="password confirmation" placeholder="Password confirmation" value="{{ cpassword }}">
            
            <br><br>

            <p2>Email</p2>
            <input type="email" name="email" placeholder="email" value="{{ email }}">
            
            <br><br>

            <p2>Name</p2>
            <input type="text" name="firstname" placeholder="First name" value="{{ first_name }}">
            <input type="text" name="lastname" placeholder="Last name" value="{{ last_name }}">
            <input type="submit" value="sign up">
        </form>
    </div>

    
    <br>
    <p1>Already a member?</p1>
    <br>
    <a href="{% url 'users:login' %}"><p1>Log in</p1></a>

</div>

{% endblock %}

users/templates/users/userprofile.html
{% include 'questionic/layout.html' %}
{% block body %}

<div class="container">
    <div class="row g-0">
      <div class="col-3"></div>
      <div class="col-6">
        <br>
        <table style="width: 100%;">
          <tr>
            <td><h1>{{ username }}</h1></td>
            <td>
              <a href="{% url 'users:follow' status=follow_status userf=username %}"><button class="button">{{ follow_status }}</button></a>
            </td>
          </tr>
        </table>
        
        <br>

        <table style="width: 100%; text-align: center;">
            <tr>
                {% if post_history.count == '' %}
                <td>0</td>
                {% else %}
                <td>{{ post_history.count }}</td>
                {% endif %} 
                <td>{{ following }}</td>
                <td>{{ follower }}</td>
            </tr>
            <tr>
                <th>post</th>
                <th>following</th>
                <th>follower</th>
            </tr>
        </table>

        

        <br>

        <h3>โพสต์ของ{{ username }}</h3>

        <div style="height: 300px; width:100%; overflow:scroll; border:1px solid #ccc;">
          {% for question in post_history %}

              <div class="card mb-5">
                  <div class="card-body" style="padding:20px 30px 10px 20px;">

                      <a href="{% url "questionic:question" question.id%}">โพสต์: {{question.title|truncatechars:50}}</a>  
                      <p>หมวดหมู่ : {{question.category}} {{question.grade}}</p>
                      {% if question.date_asked.day <= time_now.day %}
                      <p>โพสต์เมื่อ : {{question.date_asked|timesince }}</p>
                      {% else %}
                      <p>โพสต์เมื่อ : {{question.date_asked|date:'M d, Y H:i'}}</p>
                      {% endif %} 

                  </div>
              </div>
          {% empty %}
          <div class="card mb-5">
            <div class="card-body" style="padding:20px 30px 10px 20px; text-align: center;">
                <p>ยังไม่มีการโพสต์</p>
            </div>
          </div>
          {% endfor %}
        </div>

      </div>
      <div class="col-3"></div>
    </div>
  </div>



 
{% endblock %}